project_id = "snfjildozzqlyyabeyry"

[functions.payment-gateway]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.payment-reminder]
verify_jwt = false

[functions.follow-up-reminder]
verify_jwt = false

[functions.analytics-ai]
verify_jwt = true

[functions.translate]
verify_jwt = false
