/**
 * O-11: Cron — Auto-generate pre-departure checklist untuk keberangkatan
 * dalam 60 hari ke depan jika belum memiliki checklist.
 */

import {
  db, departureChecklists, packageDepartures,
  eq, and, gte, lte, sql,
} from "@workspace/db";

const CHECKLIST_TEMPLATE = [
  { hMinus: 60, category: "dokumen", item: "Cek kelengkapan paspor semua jemaah (masa berlaku min. 6 bulan)" },
  { hMinus: 60, category: "dokumen", item: "Cek kelengkapan dokumen vaksin / kartu kuning jemaah" },
  { hMinus: 60, category: "dokumen", item: "Pastikan semua jemaah sudah upload foto terbaru" },
  { hMinus: 60, category: "visa", item: "Inisiasi proses pengajuan visa ke KBSA / imigrasi" },
  { hMinus: 30, category: "hotel", item: "Konfirmasi reservasi hotel Makkah & Madinah" },
  { hMinus: 30, category: "hotel", item: "Konfirmasi tiket pesawat (nomor penerbangan, waktu)" },
  { hMinus: 30, category: "keuangan", item: "Cek sisa piutang jemaah — ingatkan yang belum lunas" },
  { hMinus: 30, category: "dokumen", item: "Pastikan semua visa sudah diproses / diajukan" },
  { hMinus: 14, category: "distribusi", item: "Mulai distribusi perlengkapan manasik (koper, baju ihram, dll)" },
  { hMinus: 14, category: "dokumen", item: "Finalisasi manifest keberangkatan" },
  { hMinus: 14, category: "penempatan", item: "Pastikan penempatan kamar hotel sudah selesai" },
  { hMinus: 14, category: "visa", item: "Semua visa jemaah harus sudah approved" },
  { hMinus: 7, category: "briefing", item: "Kirim undangan briefing / manasik ke semua jemaah via WA" },
  { hMinus: 7, category: "keuangan", item: "Final cek cicilan overdue — follow up admin keuangan" },
  { hMinus: 7, category: "penempatan", item: "Konfirmasi penempatan kursi pesawat" },
  { hMinus: 3, category: "transportasi", item: "Konfirmasi armada bus / transportasi ke bandara" },
  { hMinus: 3, category: "checkin", item: "Kirim info check-in bandara ke jemaah (waktu, titik kumpul)" },
  { hMinus: 3, category: "distribusi", item: "Pastikan semua perlengkapan sudah terdistribusi" },
];

export async function autoGenerateDepartureChecklists(): Promise<{
  scanned: number;
  generated: number;
  skipped: number;
}> {
  const today = new Date();
  const in60Days = new Date(Date.now() + 60 * 24 * 60 * 60 * 1000);

  // Get upcoming departures within 60 days
  const departures = await db
    .select({ id: packageDepartures.id, departureDate: packageDepartures.departureDate })
    .from(packageDepartures)
    .where(
      and(
        gte(packageDepartures.departureDate, today.toISOString().slice(0, 10)),
        lte(packageDepartures.departureDate, in60Days.toISOString().slice(0, 10)),
      ),
    );

  let generated = 0;
  let skipped = 0;

  for (const dep of departures) {
    // Check if this departure already has checklist items
    const [countRow] = await db
      .select({ cnt: sql<number>`count(*)::int` })
      .from(departureChecklists)
      .where(eq(departureChecklists.departureId, dep.id));

    if ((countRow?.cnt ?? 0) > 0) {
      skipped++;
      continue;
    }

    // Generate default checklist
    for (const tmpl of CHECKLIST_TEMPLATE) {
      await db.insert(departureChecklists).values({
        id: crypto.randomUUID(),
        departureId: dep.id,
        hMinus: tmpl.hMinus,
        category: tmpl.category,
        item: tmpl.item,
        isDone: false,
        createdAt: new Date(),
      });
    }
    generated++;
  }

  console.log(`[checklist-cron] scanned=${departures.length} generated=${generated} skipped=${skipped}`);
  return { scanned: departures.length, generated, skipped };
}
