// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/booking-revamp/BookingDetail.tsx": () => import("../components/mockups/booking-revamp/BookingDetail.tsx"),
  "./components/mockups/booking-revamp/BookingTable.tsx": () => import("../components/mockups/booking-revamp/BookingTable.tsx")
};
